// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace progetto_studente.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240418153601_second_migration")]
    partial class second_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Corso", b =>
                {
                    b.Property<int>("corsoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("corsoId"));

                    b.Property<string>("nomeCorso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("corsoId");

                    b.ToTable("Corsi");
                });

            modelBuilder.Entity("Studente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("corsoId")
                        .HasColumnType("int");

                    b.Property<string>("nomeStudente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("corsoId");

                    b.ToTable("Studenti");
                });

            modelBuilder.Entity("Studente", b =>
                {
                    b.HasOne("Corso", "corso")
                        .WithMany("studenti")
                        .HasForeignKey("corsoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("corso");
                });

            modelBuilder.Entity("Corso", b =>
                {
                    b.Navigation("studenti");
                });
#pragma warning restore 612, 618
        }
    }
}
